#1317 Oracle type INTERVALDS not properly displayed  The problem occurred when SQuirreL encountered an unknown SQL-Type and decided not to read the data,  see menu File --> Global Preferences --> tab Data Type Controls --> Section Unknown Data Types
==> res.wasNull() was called without reading data. Error message was:
java.sql.SQLException: Keine Daten gelesen
	at oracle.jdbc.driver.OracleStatement.wasNullValue(OracleStatement.java:3918)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.wasNull(InsensitiveScrollableResultSet.java:206)
	at net.sourceforge.squirrel_sql.fw.datasetviewer.cellcomponent.DataTypeUnknown.readResultSet(DataTypeUnknown.java:344)